// <auto-generated />
using BTL_ClothesStore.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_ClothesStore.Migrations
{
    [DbContext(typeof(BTL_ClothesStoreContext))]
    [Migration("20230402035156_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("InStock")
                        .HasColumnType("int")
                        .HasColumnName("inStock");

                    b.Property<int>("OutOfStock")
                        .HasColumnType("int")
                        .HasColumnName("outOfStock");

                    b.HasKey("Id");

                    b.ToTable("Availability", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<int>("ModifiedAt")
                        .HasColumnType("int")
                        .HasColumnName("modified_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quanlity")
                        .HasColumnType("int")
                        .HasColumnName("quanlity");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int")
                        .HasColumnName("shopping_cart_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("Cart_Item", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<int>("ModifiedAt")
                        .HasColumnType("int")
                        .HasColumnName("modified_at");

                    b.Property<int>("Name")
                        .HasColumnType("int")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<int>("ModifiedAt")
                        .HasColumnType("int")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("order_status_id");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Order_details", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quanlity")
                        .HasColumnType("int")
                        .HasColumnName("quanlity");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("Order_Items", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Name")
                        .HasColumnType("int")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Order_Status", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AvaliablityId")
                        .HasColumnType("int")
                        .HasColumnName("avaliablity_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<int>("Description")
                        .HasColumnType("int")
                        .HasColumnName("description");

                    b.Property<int>("Image")
                        .HasColumnType("int")
                        .HasColumnName("image");

                    b.Property<int>("ModifiedAt")
                        .HasColumnType("int")
                        .HasColumnName("modified_at");

                    b.Property<int>("Name")
                        .HasColumnType("int")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("AvaliablityId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("int")
                        .HasColumnName("created_at");

                    b.Property<int>("ModifiedAt")
                        .HasColumnType("int")
                        .HasColumnName("modified_at");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("shopping_cart", (string)null);
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.CartItem", b =>
                {
                    b.HasOne("BTL_ClothesStore.Models.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart_Item__produ__44FF419A");

                    b.HasOne("BTL_ClothesStore.Models.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart_Item__shopp__45F365D3");

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderDetail", b =>
                {
                    b.HasOne("BTL_ClothesStore.Models.Entities.OrderStatus", "OrderStatus")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderStatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_det__order__4222D4EF");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("BTL_ClothesStore.Models.Entities.OrderDetail", "OrderDetail")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Ite__order__49C3F6B7");

                    b.HasOne("BTL_ClothesStore.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_Ite__produ__48CFD27E");

                    b.Navigation("OrderDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Product", b =>
                {
                    b.HasOne("BTL_ClothesStore.Models.Entities.Availability", "Avaliablity")
                        .WithMany("Products")
                        .HasForeignKey("AvaliablityId")
                        .IsRequired()
                        .HasConstraintName("FK__Product__avaliab__3F466844");

                    b.HasOne("BTL_ClothesStore.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Product__categor__3E52440B");

                    b.Navigation("Avaliablity");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Availability", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderDetail", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.OrderStatus", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BTL_ClothesStore.Models.Entities.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
